name: Build Unreal Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]

    env:
      UE_PATH: "D:\\UE\\Epic Games\\UE_5.5"
      PROJECT_PATH: "D:\\git\\2nd-Team3-Final-Project\\MyGame.uproject"
      OUTPUT_DIR: "D:\\git\\2nd-Team3-Final-Project\\BuildOutput"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Package Game
        run: |
          "${{ env.UE_PATH }}\\Engine\\Build\\BatchFiles\\RunUAT.bat" BuildCookRun ^
            -project="${{ env.PROJECT_PATH }}" ^
            -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development ^
            -cook -build -stage -pak -archive ^
            -archivedirectory="${{ env.OUTPUT_DIR }}"